//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudEyesService.gradingServeice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="spyne.examples.hello.soap", ConfigurationName="gradingServeice.Application")]
    public interface Application {
        
        // CODEGEN: 操作 glioma_grading 以后生成的消息协定不是 RPC，也不是换行文档。
        [System.ServiceModel.OperationContractAttribute(Action="glioma_grading", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CloudEyesService.gradingServeice.glioma_gradingResponse1 glioma_grading(CloudEyesService.gradingServeice.glioma_grading1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="glioma_grading", ReplyAction="*")]
        System.Threading.Tasks.Task<CloudEyesService.gradingServeice.glioma_gradingResponse1> glioma_gradingAsync(CloudEyesService.gradingServeice.glioma_grading1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="spyne.examples.hello.soap")]
    public partial class glioma_grading : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string imageField;
        
        private string maskField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string image {
            get {
                return this.imageField;
            }
            set {
                this.imageField = value;
                this.RaisePropertyChanged("image");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string mask {
            get {
                return this.maskField;
            }
            set {
                this.maskField = value;
                this.RaisePropertyChanged("mask");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="spyne.examples.hello.soap")]
    public partial class glioma_gradingResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] glioma_gradingResultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=0)]
        public string[] glioma_gradingResult {
            get {
                return this.glioma_gradingResultField;
            }
            set {
                this.glioma_gradingResultField = value;
                this.RaisePropertyChanged("glioma_gradingResult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class glioma_grading1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="spyne.examples.hello.soap", Order=0)]
        public CloudEyesService.gradingServeice.glioma_grading glioma_grading;
        
        public glioma_grading1() {
        }
        
        public glioma_grading1(CloudEyesService.gradingServeice.glioma_grading glioma_grading) {
            this.glioma_grading = glioma_grading;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class glioma_gradingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="spyne.examples.hello.soap", Order=0)]
        public CloudEyesService.gradingServeice.glioma_gradingResponse glioma_gradingResponse;
        
        public glioma_gradingResponse1() {
        }
        
        public glioma_gradingResponse1(CloudEyesService.gradingServeice.glioma_gradingResponse glioma_gradingResponse) {
            this.glioma_gradingResponse = glioma_gradingResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationChannel : CloudEyesService.gradingServeice.Application, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationClient : System.ServiceModel.ClientBase<CloudEyesService.gradingServeice.Application>, CloudEyesService.gradingServeice.Application {
        
        public ApplicationClient() {
        }
        
        public ApplicationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ApplicationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ApplicationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CloudEyesService.gradingServeice.glioma_gradingResponse1 CloudEyesService.gradingServeice.Application.glioma_grading(CloudEyesService.gradingServeice.glioma_grading1 request) {
            return base.Channel.glioma_grading(request);
        }
        
        public CloudEyesService.gradingServeice.glioma_gradingResponse glioma_grading(CloudEyesService.gradingServeice.glioma_grading glioma_grading1) {
            CloudEyesService.gradingServeice.glioma_grading1 inValue = new CloudEyesService.gradingServeice.glioma_grading1();
            inValue.glioma_grading = glioma_grading1;
            CloudEyesService.gradingServeice.glioma_gradingResponse1 retVal = ((CloudEyesService.gradingServeice.Application)(this)).glioma_grading(inValue);
            return retVal.glioma_gradingResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CloudEyesService.gradingServeice.glioma_gradingResponse1> CloudEyesService.gradingServeice.Application.glioma_gradingAsync(CloudEyesService.gradingServeice.glioma_grading1 request) {
            return base.Channel.glioma_gradingAsync(request);
        }
        
        public System.Threading.Tasks.Task<CloudEyesService.gradingServeice.glioma_gradingResponse1> glioma_gradingAsync(CloudEyesService.gradingServeice.glioma_grading glioma_grading) {
            CloudEyesService.gradingServeice.glioma_grading1 inValue = new CloudEyesService.gradingServeice.glioma_grading1();
            inValue.glioma_grading = glioma_grading;
            return ((CloudEyesService.gradingServeice.Application)(this)).glioma_gradingAsync(inValue);
        }
    }
}
